version: '3.4'

services:
  sql:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      - SA_PASSWORD=123456
      - ACCEPT_EULA=Y
    volumes:
      - sql-data:/var/opt/mssql/data
    ports:
      - '5001:5001'
  catalog-api:
    build: 
        context: .
        dockerfile: Catalog.API/Dockerfile
    environment:      
      - ConnectionStrings__CatalogConnection=Data Source=127.0.0.1,5001;InitialCatalog=Catalogdb;User Id=sa;Password=123456;Encrypt=false;
    depends_on:
      - sql
    ports:
      - '5002:5002'
  webmvc:
    build: 
        context: .
        dockerfile: WebMVC/Dockerfile    
    depends_on:
      - sql
      - catalog-api
    environment:
      - 'catalog-api-url=http://host.docker.internal:5002'
    ports:
      - '5003:5003'
volumes:
    sql-data:  
     