version: '3.4'

services:
  sql:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    user: root
    environment:
      - MSSQL_SA_PASSWORD=!PasswordOkey
      - ACCEPT_EULA=Y
    volumes:
      - mssql_server_data:/var/opt/mssql/data
    ports:
      - '5433:1433'
  catalog-api:
    build: 
       context: .
       dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:              
      - ConnectionStrings__CatalogConnection=Server=sql;Database=Catalogdb;User Id=sa;Password=!PasswordOkey;Encrypt=false;TrustServerCertificate=true;
      - BaseUri=http://host.docker.internal:5002/
    depends_on:
      - sql
    ports:
      - '5002:8080'
  webmvc:
    build: 
       context: .
       dockerfile: WebMVC/Dockerfile
    depends_on:
      - sql
      - catalog-api
    environment:
      - CatalogApiUrl=http://host.docker.internal:5002/
      - SelfUrl=http://host.docker.internal:5003/
    ports:
      - '5003:8080'
volumes:
    mssql_server_data:  
     