version: '3.4'

services:
  sql:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    user: root
    environment:
      - MSSQL_SA_PASSWORD=!PasswordOkey
      - ACCEPT_EULA=Y
    volumes:
      - ./MyDockerData:/var/opt/mssql/data
    ports:
      - '5433:1433'
  catalog-api:
    build: 
       context: .
       dockerfile: Catalog.API/Dockerfile
    environment:              
      - ConnectionStrings__CatalogConnection=Server=sql;Database=Catalogdb;User Id=sa;Password=!PasswordOkey;Encrypt=false;TrustServerCertificate=true;
    depends_on:
      - sql
    ports:
      - '5002:80'
  webmvc:
    build: 
       context: .
       dockerfile: WebMVC/Dockerfile
    depends_on:
      - sql
      - catalog-api
    environment:
      - CatalogApiUrl=http://host.docker.internal:5002/
    ports:
      - '5003:80'
# volumes:
#     mssql_server_data:  
     